// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// multiply_lr_cpp
arma::sp_mat multiply_lr_cpp(const arma::sp_mat& impL, const arma::sp_mat& Lmap, const arma::sp_mat& impR, const arma::sp_mat& Rmap);
RcppExport SEXP _cytosignal_multiply_lr_cpp(SEXP impLSEXP, SEXP LmapSEXP, SEXP impRSEXP, SEXP RmapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type impL(impLSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type Lmap(LmapSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type impR(impRSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type Rmap(RmapSEXP);
    rcpp_result_gen = Rcpp::wrap(multiply_lr_cpp(impL, Lmap, impR, Rmap));
    return rcpp_result_gen;
END_RCPP
}
// findInterval_leftOpen_cpp
arma::uword findInterval_leftOpen_cpp(double x, const arma::vec& breaks);
RcppExport SEXP _cytosignal_findInterval_leftOpen_cpp(SEXP xSEXP, SEXP breaksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type breaks(breaksSEXP);
    rcpp_result_gen = Rcpp::wrap(findInterval_leftOpen_cpp(x, breaks));
    return rcpp_result_gen;
END_RCPP
}
// perm_test_Rcpp
arma::sp_mat perm_test_Rcpp(const arma::sp_mat& raw, const arma::vec& libSize, const arma::uvec& intrType, Rcpp::List diff_lig_NGL, Rcpp::List diff_recep_NGL, Rcpp::List diff_dtAvg_NGL, Rcpp::List diff_smooth_NGL, Rcpp::List cont_lig_NGL, Rcpp::List cont_recep_NGL, Rcpp::List cont_dtAvg_NGL, Rcpp::List cont_smooth_NGL, const arma::sp_mat& Lmap, const arma::sp_mat& Rmap, const arma::sp_mat& lrscore);
RcppExport SEXP _cytosignal_perm_test_Rcpp(SEXP rawSEXP, SEXP libSizeSEXP, SEXP intrTypeSEXP, SEXP diff_lig_NGLSEXP, SEXP diff_recep_NGLSEXP, SEXP diff_dtAvg_NGLSEXP, SEXP diff_smooth_NGLSEXP, SEXP cont_lig_NGLSEXP, SEXP cont_recep_NGLSEXP, SEXP cont_dtAvg_NGLSEXP, SEXP cont_smooth_NGLSEXP, SEXP LmapSEXP, SEXP RmapSEXP, SEXP lrscoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type raw(rawSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type libSize(libSizeSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type intrType(intrTypeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type diff_lig_NGL(diff_lig_NGLSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type diff_recep_NGL(diff_recep_NGLSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type diff_dtAvg_NGL(diff_dtAvg_NGLSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type diff_smooth_NGL(diff_smooth_NGLSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type cont_lig_NGL(cont_lig_NGLSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type cont_recep_NGL(cont_recep_NGLSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type cont_dtAvg_NGL(cont_dtAvg_NGLSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type cont_smooth_NGL(cont_smooth_NGLSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type Lmap(LmapSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type Rmap(RmapSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type lrscore(lrscoreSEXP);
    rcpp_result_gen = Rcpp::wrap(perm_test_Rcpp(raw, libSize, intrType, diff_lig_NGL, diff_recep_NGL, diff_dtAvg_NGL, diff_smooth_NGL, cont_lig_NGL, cont_recep_NGL, cont_dtAvg_NGL, cont_smooth_NGL, Lmap, Rmap, lrscore));
    return rcpp_result_gen;
END_RCPP
}
// spatialGraphFDR_cpp
arma::mat spatialGraphFDR_cpp(const arma::mat& pval, const arma::uvec& intrType, const arma::sp_mat& contGraph);
RcppExport SEXP _cytosignal_spatialGraphFDR_cpp(SEXP pvalSEXP, SEXP intrTypeSEXP, SEXP contGraphSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type pval(pvalSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type intrType(intrTypeSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type contGraph(contGraphSEXP);
    rcpp_result_gen = Rcpp::wrap(spatialGraphFDR_cpp(pval, intrType, contGraph));
    return rcpp_result_gen;
END_RCPP
}
// clusterWiseLRscore_cpp
arma::cube clusterWiseLRscore_cpp(const arma::sp_mat& raw, const arma::uvec& libSize, const arma::uvec& clusterInt, const arma::uword& nCluster, const arma::uvec& intrType, const arma::sp_mat& diff_lig_graph, const arma::sp_mat& cont_lig_graph, const arma::sp_mat& recep_graph, const arma::sp_mat& dtAvg_graph, const arma::sp_mat& Lmap, const arma::sp_mat& Rmap);
RcppExport SEXP _cytosignal_clusterWiseLRscore_cpp(SEXP rawSEXP, SEXP libSizeSEXP, SEXP clusterIntSEXP, SEXP nClusterSEXP, SEXP intrTypeSEXP, SEXP diff_lig_graphSEXP, SEXP cont_lig_graphSEXP, SEXP recep_graphSEXP, SEXP dtAvg_graphSEXP, SEXP LmapSEXP, SEXP RmapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type raw(rawSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type libSize(libSizeSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type clusterInt(clusterIntSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type nCluster(nClusterSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type intrType(intrTypeSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type diff_lig_graph(diff_lig_graphSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type cont_lig_graph(cont_lig_graphSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type recep_graph(recep_graphSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type dtAvg_graph(dtAvg_graphSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type Lmap(LmapSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type Rmap(RmapSEXP);
    rcpp_result_gen = Rcpp::wrap(clusterWiseLRscore_cpp(raw, libSize, clusterInt, nCluster, intrType, diff_lig_graph, cont_lig_graph, recep_graph, dtAvg_graph, Lmap, Rmap));
    return rcpp_result_gen;
END_RCPP
}
// gauss_vec_cpp
NumericVector gauss_vec_cpp(NumericVector x, double sigma);
RcppExport SEXP _cytosignal_gauss_vec_cpp(SEXP xSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(gauss_vec_cpp(x, sigma));
    return rcpp_result_gen;
END_RCPP
}
// rep_each_cpp
arma::vec rep_each_cpp(int l, int n);
RcppExport SEXP _cytosignal_rep_each_cpp(SEXP lSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type l(lSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(rep_each_cpp(l, n));
    return rcpp_result_gen;
END_RCPP
}
// meanMat_cpp
arma::sp_mat meanMat_cpp(const List& l, int nrow, int ncol);
RcppExport SEXP _cytosignal_meanMat_cpp(SEXP lSEXP, SEXP nrowSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type l(lSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    rcpp_result_gen = Rcpp::wrap(meanMat_cpp(l, nrow, ncol));
    return rcpp_result_gen;
END_RCPP
}
// stdMat_cpp
arma::mat stdMat_cpp(const arma::mat& x);
RcppExport SEXP _cytosignal_stdMat_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(stdMat_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// pearson_col_cpp
arma::vec pearson_col_cpp(const arma::mat& x, const arma::mat& y);
RcppExport SEXP _cytosignal_pearson_col_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(pearson_col_cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// cbind_list
arma::sp_mat cbind_list(List& sparse_matrix_list);
RcppExport SEXP _cytosignal_cbind_list(SEXP sparse_matrix_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type sparse_matrix_list(sparse_matrix_listSEXP);
    rcpp_result_gen = Rcpp::wrap(cbind_list(sparse_matrix_list));
    return rcpp_result_gen;
END_RCPP
}
// rbind_list
arma::sp_mat rbind_list(List sparse_matrix_list);
RcppExport SEXP _cytosignal_rbind_list(SEXP sparse_matrix_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type sparse_matrix_list(sparse_matrix_listSEXP);
    rcpp_result_gen = Rcpp::wrap(rbind_list(sparse_matrix_list));
    return rcpp_result_gen;
END_RCPP
}
// cleanLRscore_sparse_cpp
arma::sp_mat cleanLRscore_sparse_cpp(arma::uvec i, arma::uvec p, arma::colvec x, const int nrow, const int ncol);
RcppExport SEXP _cytosignal_cleanLRscore_sparse_cpp(SEXP iSEXP, SEXP pSEXP, SEXP xSEXP, SEXP nrowSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uvec >::type i(iSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type p(pSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< const int >::type ncol(ncolSEXP);
    rcpp_result_gen = Rcpp::wrap(cleanLRscore_sparse_cpp(i, p, x, nrow, ncol));
    return rcpp_result_gen;
END_RCPP
}
// select_EB_rcpp2
arma::sp_mat select_EB_rcpp2(const arma::mat& loc, const double eps);
RcppExport SEXP _cytosignal_select_EB_rcpp2(SEXP locSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type loc(locSEXP);
    Rcpp::traits::input_parameter< const double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(select_EB_rcpp2(loc, eps));
    return rcpp_result_gen;
END_RCPP
}
// gauss_vec_inplace_cpp
void gauss_vec_inplace_cpp(NumericVector& x, const double sigma);
RcppExport SEXP _cytosignal_gauss_vec_inplace_cpp(SEXP xSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma(sigmaSEXP);
    gauss_vec_inplace_cpp(x, sigma);
    return R_NilValue;
END_RCPP
}
// normalizeSparse_cpp
arma::sp_mat normalizeSparse_cpp(const arma::sp_mat& x);
RcppExport SEXP _cytosignal_normalizeSparse_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(normalizeSparse_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// euclidean_elementwise_cpp
NumericVector euclidean_elementwise_cpp(const arma::mat& x, const arma::mat& y);
RcppExport SEXP _cytosignal_euclidean_elementwise_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(euclidean_elementwise_cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// inferScoreLR_cpp
arma::mat inferScoreLR_cpp(const arma::mat& dge_lig, const arma::mat& dge_recep, const arma::uvec& lig_index, const arma::uvec& lig_list, const arma::uvec& recep_index, const arma::uvec& recep_list);
RcppExport SEXP _cytosignal_inferScoreLR_cpp(SEXP dge_ligSEXP, SEXP dge_recepSEXP, SEXP lig_indexSEXP, SEXP lig_listSEXP, SEXP recep_indexSEXP, SEXP recep_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type dge_lig(dge_ligSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dge_recep(dge_recepSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type lig_index(lig_indexSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type lig_list(lig_listSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type recep_index(recep_indexSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type recep_list(recep_listSEXP);
    rcpp_result_gen = Rcpp::wrap(inferScoreLR_cpp(dge_lig, dge_recep, lig_index, lig_list, recep_index, recep_list));
    return rcpp_result_gen;
END_RCPP
}
// inferVeloLR_cpp
arma::mat inferVeloLR_cpp(const arma::mat& dge_lig, const arma::mat& dge_recep, const arma::mat& dge_lig_velo, const arma::mat& dge_recep_velo, const arma::uvec& lig_index, const arma::uvec& lig_list, const arma::uvec& recep_index, const arma::uvec& recep_list);
RcppExport SEXP _cytosignal_inferVeloLR_cpp(SEXP dge_ligSEXP, SEXP dge_recepSEXP, SEXP dge_lig_veloSEXP, SEXP dge_recep_veloSEXP, SEXP lig_indexSEXP, SEXP lig_listSEXP, SEXP recep_indexSEXP, SEXP recep_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type dge_lig(dge_ligSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dge_recep(dge_recepSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dge_lig_velo(dge_lig_veloSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dge_recep_velo(dge_recep_veloSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type lig_index(lig_indexSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type lig_list(lig_listSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type recep_index(recep_indexSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type recep_list(recep_listSEXP);
    rcpp_result_gen = Rcpp::wrap(inferVeloLR_cpp(dge_lig, dge_recep, dge_lig_velo, dge_recep_velo, lig_index, lig_list, recep_index, recep_list));
    return rcpp_result_gen;
END_RCPP
}
// graphNicheLR_cpp
arma::mat graphNicheLR_cpp(const arma::mat& dge_lig, const arma::mat& dge_recep, const arma::uvec& lig_index, const arma::uvec& lig_list, const arma::uvec& recep_index, const arma::uvec& recep_list, const arma::uvec& nb_index, const arma::uvec& nb_list);
RcppExport SEXP _cytosignal_graphNicheLR_cpp(SEXP dge_ligSEXP, SEXP dge_recepSEXP, SEXP lig_indexSEXP, SEXP lig_listSEXP, SEXP recep_indexSEXP, SEXP recep_listSEXP, SEXP nb_indexSEXP, SEXP nb_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type dge_lig(dge_ligSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dge_recep(dge_recepSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type lig_index(lig_indexSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type lig_list(lig_listSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type recep_index(recep_indexSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type recep_list(recep_listSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type nb_index(nb_indexSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type nb_list(nb_listSEXP);
    rcpp_result_gen = Rcpp::wrap(graphNicheLR_cpp(dge_lig, dge_recep, lig_index, lig_list, recep_index, recep_list, nb_index, nb_list));
    return rcpp_result_gen;
END_RCPP
}
// VelographNicheLR_cpp
arma::mat VelographNicheLR_cpp(const arma::mat& dge_lig, const arma::mat& dge_recep, const arma::mat& dge_velo, const arma::uvec& lig_index, const arma::uvec& lig_list, const arma::uvec& recep_index, const arma::uvec& recep_list, const arma::uvec& nb_index, const arma::uvec& nb_list);
RcppExport SEXP _cytosignal_VelographNicheLR_cpp(SEXP dge_ligSEXP, SEXP dge_recepSEXP, SEXP dge_veloSEXP, SEXP lig_indexSEXP, SEXP lig_listSEXP, SEXP recep_indexSEXP, SEXP recep_listSEXP, SEXP nb_indexSEXP, SEXP nb_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type dge_lig(dge_ligSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dge_recep(dge_recepSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dge_velo(dge_veloSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type lig_index(lig_indexSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type lig_list(lig_listSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type recep_index(recep_indexSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type recep_list(recep_listSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type nb_index(nb_indexSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type nb_list(nb_listSEXP);
    rcpp_result_gen = Rcpp::wrap(VelographNicheLR_cpp(dge_lig, dge_recep, dge_velo, lig_index, lig_list, recep_index, recep_list, nb_index, nb_list));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rank_matrix_dgc
std::vector<std::list<float> > cpp_rank_matrix_dgc(arma::vec& x, const arma::vec& p, int nrow, int ncol);
RcppExport SEXP _cytosignal_cpp_rank_matrix_dgc(SEXP xSEXP, SEXP pSEXP, SEXP nrowSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rank_matrix_dgc(x, p, nrow, ncol));
    return rcpp_result_gen;
END_RCPP
}
// rowAggregateSum_sparse
arma::mat rowAggregateSum_sparse(arma::sp_mat& X, const arma::uvec& groups, unsigned ngroups);
RcppExport SEXP _cytosignal_rowAggregateSum_sparse(SEXP XSEXP, SEXP groupsSEXP, SEXP ngroupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< unsigned >::type ngroups(ngroupsSEXP);
    rcpp_result_gen = Rcpp::wrap(rowAggregateSum_sparse(X, groups, ngroups));
    return rcpp_result_gen;
END_RCPP
}
// colAggregateSum_sparse
arma::mat colAggregateSum_sparse(arma::sp_mat& X, const arma::uvec& groups, unsigned ngroups);
RcppExport SEXP _cytosignal_colAggregateSum_sparse(SEXP XSEXP, SEXP groupsSEXP, SEXP ngroupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< unsigned >::type ngroups(ngroupsSEXP);
    rcpp_result_gen = Rcpp::wrap(colAggregateSum_sparse(X, groups, ngroups));
    return rcpp_result_gen;
END_RCPP
}
// colNNZAggr_sparse
arma::mat colNNZAggr_sparse(arma::sp_mat& X, const arma::uvec& groups, unsigned ngroups);
RcppExport SEXP _cytosignal_colNNZAggr_sparse(SEXP XSEXP, SEXP groupsSEXP, SEXP ngroupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< unsigned >::type ngroups(ngroupsSEXP);
    rcpp_result_gen = Rcpp::wrap(colNNZAggr_sparse(X, groups, ngroups));
    return rcpp_result_gen;
END_RCPP
}
// rowNNZAggr_sparse
arma::mat rowNNZAggr_sparse(arma::sp_mat& X, const arma::uvec& groups, unsigned ngroups);
RcppExport SEXP _cytosignal_rowNNZAggr_sparse(SEXP XSEXP, SEXP groupsSEXP, SEXP ngroupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< unsigned >::type ngroups(ngroupsSEXP);
    rcpp_result_gen = Rcpp::wrap(rowNNZAggr_sparse(X, groups, ngroups));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cytosignal_multiply_lr_cpp", (DL_FUNC) &_cytosignal_multiply_lr_cpp, 4},
    {"_cytosignal_findInterval_leftOpen_cpp", (DL_FUNC) &_cytosignal_findInterval_leftOpen_cpp, 2},
    {"_cytosignal_perm_test_Rcpp", (DL_FUNC) &_cytosignal_perm_test_Rcpp, 14},
    {"_cytosignal_spatialGraphFDR_cpp", (DL_FUNC) &_cytosignal_spatialGraphFDR_cpp, 3},
    {"_cytosignal_clusterWiseLRscore_cpp", (DL_FUNC) &_cytosignal_clusterWiseLRscore_cpp, 11},
    {"_cytosignal_gauss_vec_cpp", (DL_FUNC) &_cytosignal_gauss_vec_cpp, 2},
    {"_cytosignal_rep_each_cpp", (DL_FUNC) &_cytosignal_rep_each_cpp, 2},
    {"_cytosignal_meanMat_cpp", (DL_FUNC) &_cytosignal_meanMat_cpp, 3},
    {"_cytosignal_stdMat_cpp", (DL_FUNC) &_cytosignal_stdMat_cpp, 1},
    {"_cytosignal_pearson_col_cpp", (DL_FUNC) &_cytosignal_pearson_col_cpp, 2},
    {"_cytosignal_cbind_list", (DL_FUNC) &_cytosignal_cbind_list, 1},
    {"_cytosignal_rbind_list", (DL_FUNC) &_cytosignal_rbind_list, 1},
    {"_cytosignal_cleanLRscore_sparse_cpp", (DL_FUNC) &_cytosignal_cleanLRscore_sparse_cpp, 5},
    {"_cytosignal_select_EB_rcpp2", (DL_FUNC) &_cytosignal_select_EB_rcpp2, 2},
    {"_cytosignal_gauss_vec_inplace_cpp", (DL_FUNC) &_cytosignal_gauss_vec_inplace_cpp, 2},
    {"_cytosignal_normalizeSparse_cpp", (DL_FUNC) &_cytosignal_normalizeSparse_cpp, 1},
    {"_cytosignal_euclidean_elementwise_cpp", (DL_FUNC) &_cytosignal_euclidean_elementwise_cpp, 2},
    {"_cytosignal_inferScoreLR_cpp", (DL_FUNC) &_cytosignal_inferScoreLR_cpp, 6},
    {"_cytosignal_inferVeloLR_cpp", (DL_FUNC) &_cytosignal_inferVeloLR_cpp, 8},
    {"_cytosignal_graphNicheLR_cpp", (DL_FUNC) &_cytosignal_graphNicheLR_cpp, 8},
    {"_cytosignal_VelographNicheLR_cpp", (DL_FUNC) &_cytosignal_VelographNicheLR_cpp, 9},
    {"_cytosignal_cpp_rank_matrix_dgc", (DL_FUNC) &_cytosignal_cpp_rank_matrix_dgc, 4},
    {"_cytosignal_rowAggregateSum_sparse", (DL_FUNC) &_cytosignal_rowAggregateSum_sparse, 3},
    {"_cytosignal_colAggregateSum_sparse", (DL_FUNC) &_cytosignal_colAggregateSum_sparse, 3},
    {"_cytosignal_colNNZAggr_sparse", (DL_FUNC) &_cytosignal_colNNZAggr_sparse, 3},
    {"_cytosignal_rowNNZAggr_sparse", (DL_FUNC) &_cytosignal_rowNNZAggr_sparse, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_cytosignal(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
