# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gauss_vec_cpp <- function(x, sigma) {
    .Call('_cytosignal_gauss_vec_cpp', PACKAGE = 'cytosignal', x, sigma)
}

rep_each_cpp <- function(l, n) {
    .Call('_cytosignal_rep_each_cpp', PACKAGE = 'cytosignal', l, n)
}

meanMat_cpp <- function(l, nrow, ncol) {
    .Call('_cytosignal_meanMat_cpp', PACKAGE = 'cytosignal', l, nrow, ncol)
}

stdMat_cpp <- function(x) {
    .Call('_cytosignal_stdMat_cpp', PACKAGE = 'cytosignal', x)
}

pearson_col_cpp <- function(x, y) {
    .Call('_cytosignal_pearson_col_cpp', PACKAGE = 'cytosignal', x, y)
}

cbind_list <- function(sparse_matrix_list) {
    .Call('_cytosignal_cbind_list', PACKAGE = 'cytosignal', sparse_matrix_list)
}

rbind_list <- function(sparse_matrix_list) {
    .Call('_cytosignal_rbind_list', PACKAGE = 'cytosignal', sparse_matrix_list)
}

inferScoreLR_cpp <- function(dge_lig, dge_recep, lig_index, lig_list, recep_index, recep_list) {
    .Call('_cytosignal_inferScoreLR_cpp', PACKAGE = 'cytosignal', dge_lig, dge_recep, lig_index, lig_list, recep_index, recep_list)
}

inferVeloLR_cpp <- function(dge_lig, dge_recep, dge_lig_velo, dge_recep_velo, lig_index, lig_list, recep_index, recep_list) {
    .Call('_cytosignal_inferVeloLR_cpp', PACKAGE = 'cytosignal', dge_lig, dge_recep, dge_lig_velo, dge_recep_velo, lig_index, lig_list, recep_index, recep_list)
}

graphNicheLR_cpp <- function(dge_lig, dge_recep, lig_index, lig_list, recep_index, recep_list, nb_index, nb_list) {
    .Call('_cytosignal_graphNicheLR_cpp', PACKAGE = 'cytosignal', dge_lig, dge_recep, lig_index, lig_list, recep_index, recep_list, nb_index, nb_list)
}

VelographNicheLR_cpp <- function(dge_lig, dge_recep, dge_velo, lig_index, lig_list, recep_index, recep_list, nb_index, nb_list) {
    .Call('_cytosignal_VelographNicheLR_cpp', PACKAGE = 'cytosignal', dge_lig, dge_recep, dge_velo, lig_index, lig_list, recep_index, recep_list, nb_index, nb_list)
}

